### ISSUE TITLE
Search Function Removed?

### ISSUE THREAD

**Issue by coderkei** [iluvadev/XstReader#12]
I have downloaded the latest release and the new user interface and extra features are very useful but I have noticed that I cannot find the search box anywhere to search the current folder. Has it been removed? It was a vital feature that I relied on.

This is a screenshot of the old version that shows the feature I was using:
![image](https://user-images.githubusercontent.com/7037851/207059606-202989b1-5055-44fd-96fe-3d60fd97c655.png)

Thank you.

**Comment by iluvadev** [comment]
Hi, thanks for the observation!
I created a new release with this missing functionality

You can download latest version at: https://github.com/iluvadev/XstReader/releases/tag/2022-12-13

Thanks!

**Comment by coderkei** [comment]
Thank you
