### ISSUE TITLE
Is it possible to view the raw messages headers

### ISSUE THREAD

**Issue by mbalsam-refind** [iluvadev/XstReader#15]
Is it possible to browse and export the raw messages headers.  These are the [RFC 2076] headers such as Received: from   etc.

**Comment by mbalsam-refind** [comment]
Never mind. Found it  PidTagTransportMessageHeaders

**Comment by iluvadev** [comment]
Yes is this property. Here is the documentation: [PidTagTransportMessageHeaders](https://learn.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagtransportmessageheaders-canonical-property)

**Comment by iluvadev** [comment]
In the latest release, the message panel has a tab to see all Transport Headers in a more friendly way
