### ISSUE TITLE
Exporting items to new PST

### ISSUE THREAD

**Issue by kartikeysemwal** [iluvadev/XstReader#16]
Good to know someone is maintaining https://github.com/Dijji/XstReader repo. Thanks for this.
I have doubt, though I have not checked all the functionalities yet, but I am curious to know is there any way we can export messages to a new PST.

**Comment by iluvadev** [comment]
Hi thanks for your words.
In XstReader.App there are options to export messages to Outlook .msg file format.
But, there are no options to create or edit .pst files, only can export messages (and attachments)
