### ISSUE TITLE
Emails with Multiple Attachments with Same Name - Save All and Export All Problem

### ISSUE THREAD

**Issue by tcjjr** [iluvadev/XstReader#8]
Thanks for updating this great project.

I've got some PSTs which contain emails that have multiple PDF attachments which have the same filename but they are different files with distinct content and different file sizes. Tthey're autogenerated out of a client's database and every one of them is named CFMS.getDocument.pdf. Outlook allows users to attach and send multiple attachments bearing the same name and it doesn't complain about the duplicate names.

When I tell XstReader to export all attachments or to save all attachments, it only saves one of them and not the others, apparently due to the name collision. There's no error or warning. It looks like I end up with the last of the attachment files in each instance, so I suspect the program is trying to save each of them and then overwriting each earlier one with the next file in sequence bearing the same name. Is there any way to add a "(1)" and "(2)" etc. onto the attachment filenames when there's a name collision?

I've confirmed this behavior is in the original 1.x version too.

**Comment by iluvadev** [comment]
Hi, thanks for this issue!
i can not test it now, but, it might be solved in XstReader.App, the new version of XstReader, with new GUI and more options: you can export all attachments in messages and all attachments included in all messages inside a folder (and all subfolders); attachments are ordered by date and if name exists, renamed with sufix "(1)", "(2)"...
Try this. At the moment I can not update XstExporter or "old" XstReader with this functionality. 

If this do not work with XstReader.App is a bug. Sorry.

In September i will update documentation and i will try to unify behaviors between XstExporter, XstReader and XstReader.App.

Tell me if you can export all attachments with this solution. Thanks!

**Comment by tcjjr** [comment]
Here's some additional information which might help:

I tried using XstReader.App.exe (v.2.0.0) before posting the issue, and I thought I had the same attachment-suffix problem, but now that I've tried again, I realize it was a slightly different problem. The problem with v.2 was that when I exported messages from it, individual attachment files were not saved in their native PDF format. Instead, I got individual HTML files for each message with the attachments from each message embedded as blobs within the HTML file itself, with a link provided from which I could download them from within a browser. 

I was expecting individual HTML files for each message and separate native-format attachment files in a subfolder with a name corresponding to the message name, just like the old XstReader would provide. That's what I'm hoping to achieve.

For example, exporting a message with 3 attachments (_FileName.pdf, FileName.pdf, FileName.pdf_) would yield:

 FILE: _YYYY-MM-DD HHMM MessageSubject.html_
 SUBFOLDER: _YYYY-MM-DD HHMM MessageSubject Attachments_
 FOLDER CONTENTS: _FileName.pdf, FileName (1).pdf, FileName (2).pdf_

I tried changing the Embed Attachments setting in XstReader.App.exe v.2 Settings to False but nothing seemed to change in the export behavior when I did that. I still got HTML with embedded blobs, not separate files.

After I had the problem with not getting individual attachment files saved separately in v2, I tried v.1.15.0. With that, I got separate message-text (in HTML) and attachment (native format) files, but then I had the no-suffixes problem, so duplicate-named files were lost. For a message with 3 PDF attachments, all of which bore the same filename, I got only the last-attached file bearing that name. I tried XstExporter v.2.0.1, too, with the same attachment output problem as XstReader v.1.15.0.

All of the preceding applications came from your XstReader-2022.08.15 Github release package. I also tested an old 2020 release from Dijji I'd saved (1.11.x.x) and got the same result as with v.1.15.0 as to attachments.

After doing further testing of XstReader.App.exe (v.2.0.0), I see the following behaviors in that app using these features:

<Folder/Export Attachments> or <Message/Export Attachments>:
The same-name PDF attachments do export properly as individual PDF files with (1) and (2) suffixes for each attachment after the first one. For example, when there are three PDF attachments with the same name, I get Filename.pdf, then Filename (1).pdf, then Filename (2).pdf. But with that option, I don't get the messages the attachments were contained within.

<Folder/Export All Messages in the Folder>, or <Message/Export Message> for an individual message:
Each message saves as an individual HTML file but there is no separate attachment. Each attachment is embedded in the file, encoded in the HTML, and I can download any attachment from within my browser at that point, but I don't get the individual files. When I download them, the filename suffix behavior is correct, in that they do have (1) and (2) suffixes for the ones after the first one.

<Folder/Export all Folders and Messages in Folder> for the "Top of Information Store" folder in the Folders Tree:
Each message saves as an individual HTML file, sorted into its respective folder, but there are no separate attachments. (As above, each attachment is embedded in the file, encoded in the HTML, and I can download them from within my browser at that point, but I don't get the individual files. When I download them, the filename suffix behavior is correct, in that they do have (1) and (2) suffixes for the ones after the first one.)

**Comment by iluvadev** [comment]
Thanks for the information.

As you explain, in XstReader.App the html result of a message export is always a single file, with all attachments embedded as blobs. 
I think that a solution could be adding an option to export a message with attachments as files, with suffixes if there are some collisions: saving the message as html file with a folder with its attachments.

In a few days i will update the code with this functionality.

Thanks!

**Comment by iluvadev** [comment]
Hi, I published a new release: [2022-10-10](https://github.com/iluvadev/XstReader/releases/tag/2022-10-10)

In this release there are improvements in the export options:
- All exported Attachements are saved in a folder with the message name
- You can export attachments as files when saves a message as single HTML
- You can apply patterns to the exported folder and message names

All exported files and folders uses number suffixes in case of collissions (1), (2)..

Try it and tell me something.

Thanks!
